name: Test

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  run-pytest:
    runs-on: ubuntu-latest
    env:
      SIDEFX_CLIENT: ${{secrets.SIDEFX_CLIENT}}
      SIDEFX_SECRET: ${{secrets.SIDEFX_SECRET}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[test]
      - name: Run pytest
        run: pytest tests
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .
      - name: Run isort
        if: always()
        run: |
          pip install isort
          isort . --check
      - name: Lint with Ruff
        if: always()
        run: |
          pip install ruff
          ruff --format=github .
      - name: Run black
        if: always()
        run: |
          pip install black
          black --check .